apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::963933939017:user/imrishuroy_dev
      username: imrishuroy_dev
      groups:
        - system:masters